/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111995-g5f8c113b75-20230909"
#endif /* AVUTIL_FFVERSION_H */
